image:
  name: "${QUIZ_IMAGE}"
  pullPolicy: IfNotPresent
replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 80
environment: prod
env:
  DB_URL: ${DB_URL}
  TEST_DB_URL: ${TEST_DB_URL}
  CORS_ORIGINS: ${CORS_ORIGINS}
  JWT_SECRET_KEY: ${AUTH_JWT_SECRET_KEY}
  S3_REGION: ${S3_REGION}
  S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
  S3_BUCKET: ${S3_BUCKET}
  AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
  MAX_IMAGE_SIZE: 5242880 # 5MB
  ENVIRONMENT: "production"
  DEBUG: "false"
