services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migrator:
    build:
      context: backend-python/shared
      dockerfile: Dockerfile
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS}
      DB_URL: ${DB_URL}
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    build:
      context: backend-python
      dockerfile: auth_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS}
      SECRET_KEY: ${AUTH_JWT_SECRET_KEY}
      DB_URL: ${DB_URL}
    depends_on:
      - migrator

  quiz:
    build:
      context: backend-python
      dockerfile: quiz_service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_BUCKET: ${S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      MAX_IMAGE_SIZE: ${MAX_IMAGE_SIZE}
      DB_URL: ${DB_URL}
      TEST_DB_URL: ${TEST_DB_URL}
    depends_on:
      - auth

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    depends_on:
      - quiz

#  go-backend:
#    build:
#      context: backend-go
#      dockerfile: backend-go/SessionService/Dockerfile
#    ports:
#      - "8080:8080"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge