auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

schema_config:
  configs:
  - from: "2025-07-15"
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: tsdb_
      period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-active
    cache_location: /tmp/loki/tsdb-cache
    mode: opensource
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 10
  delete_request_store: filesystem

limits_config:
  retention_period: 168h # 7 days retention
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true
