apiVersion: v1
kind: Service
metadata:
  name: real-time
spec:
  selector:
    app.kubernetes.io/name: "real-time"
  ports:
  - protocol: TCP
    port: 8080 # Service port
    targetPort: 8080 # Pod port
