image:
  name: "${LEADERBOARD_IMAGE}"
  pullPolicy: IfNotPresent
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 85
environment: prod
env:
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  RABBITMQ_HOST: "rabbit"
  RABBITMQ_PORT: "5672"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REALTIME_SERVICE_HOST: "real-time"
  REALTIME_SERVICE_PORT: "8080"
  SESSION_SERVICE_HOST: "session"
  SESSION_SERVICE_PORT: "8081"
  LEADERBOARD_SERVICE_HOST: "0.0.0.0"
  LEADERBOARD_SERVICE_PORT: "8082"
  JWT_SECRET_KEY: "${GO_JWT_SECRET_KEY}"
  ENV: "production"
