services:
  app:
    build: .
    container_name: quiz-engine
    depends_on:
      - rabbitmq
      - redis
    command:
      - quiz-engine
      - -host=0.0.0.0
      - -port=8000
      - -rabbitmq=amqp://guest:guest@rabbitmq:5672/
      - -redis=redis:6379
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
