apiVersion: apps/v1
kind: Deployment
metadata:
  name: "auth-{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "auth"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/part-of: "tryit"
    app.kubernetes.io/env: "{{ .Values.environment | default "prod" }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  revisionHistoryLimit: 12
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "auth"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "auth"
      annotations:
        prometheus.io/path: "/metrics/"
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: "auth"
        image: "{{ .Values.image.name }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
          - name: DB_URL
            value: "{{ .Values.env.DB_URL }}"
          - name: TEST_DB_URL
            value: "{{ .Values.env.TEST_DB_URL }}"
          - name: CORS_ORIGINS
            value: "{{ .Values.env.CORS_ORIGINS }}"
          - name: JWT_SECRET_KEY
            value: "{{ .Values.env.JWT_SECRET_KEY }}"
          - name: ENVIRONMENT
            value: "{{ .Values.env.ENVIRONMENT }}"
          - name: DEBUG
            value: "{{ .Values.env.DEBUG }}"
        ports:
        - name: http
          containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 2
          failureThreshold: 6
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
