image:
  name: "${REALTIME_IMAGE}"
  pullPolicy: IfNotPresent
replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  cpuUtilization: 75
environment: prod
env:
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  RABBITMQ_HOST: "rabbit"
  RABBITMQ_PORT: "5672"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REALTIME_SERVICE_HOST: "0.0.0.0"
  REALTIME_SERVICE_PORT: "8080"
  LEADERBOARD_SERVICE_HOST: "leaderboard"
  LEADERBOARD_SERVICE_PORT: "8082"
  JWT_SECRET_KEY: "${GO_JWT_SECRET_KEY}"
  ENV: "production"
