basePath: /
definitions:
  xxx_SessionService_models.CreateSessionReq:
    properties:
      quizId:
        type: string
      userId:
        type: string
    type: object
  xxx_SessionService_models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  xxx_SessionService_models.UserToken:
    properties:
      currentQuiz:
        type: string
      exp:
        type: integer
      serverWsEndpoint:
        type: string
      userId:
        type: string
      userType:
        type: string
    type: object
  xxx_SessionService_models.ValidateCodeReq:
    properties:
      code:
        type: string
      userId:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Это пример API с gorilla/mux и swaggo
  title: Пример API
  version: "1.0"
paths:
  /join:
    post:
      consumes:
      - application/json
      description: Validates a session code and returns a user token for the specified
        user if the code is valid.
      parameters:
      - description: ' Create Session req'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xxx_SessionService_models.ValidateCodeReq'
      produces:
      - application/json
      responses:
        "200":
          description: User token in JSON format
          schema:
            $ref: '#/definitions/xxx_SessionService_models.UserToken'
        "400":
          description: Invalid code
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "405":
          description: Only GET method is allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Validate session code
      tags:
      - sessions
  /session/{id}/nextQuestion:
    post:
      consumes:
      - application/json
      description: Advances to the next question in the session identified by the
        provided code.
      parameters:
      - description: Session code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully moved to the next question
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Move to the next question
      tags:
      - sessions
  /sessions:
    post:
      consumes:
      - application/json
      description: Creates a new session and returns an admin token for the specified
        user by userId.
      parameters:
      - description: ' Create Session req'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xxx_SessionService_models.CreateSessionReq'
      produces:
      - application/json
      responses:
        "200":
          description: Admin token in JSON format
          schema:
            $ref: '#/definitions/xxx_SessionService_models.UserToken'
        "405":
          description: Method not allowed, only GET is allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Create a new session and get an admin token
      tags:
      - sessions
  /start:
    post:
      consumes:
      - application/json
      description: Starts a session using the provided session ID.
      parameters:
      - description: Session ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Session started successfully
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Start a session
      tags:
      - sessions
swagger: "2.0"
