basePath: /
definitions:
  xxx_SessionService_models.CreateSessionReq:
    properties:
      quizId:
        type: string
      userId:
        type: string
      userName:
        type: string
    type: object
  xxx_SessionService_models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  xxx_SessionService_models.SessionCreateResponse:
    properties:
      jwt:
        type: string
      serverWsEndpoint:
        type: string
      sessionId:
        type: string
    type: object
  xxx_SessionService_models.ValidateCodeReq:
    properties:
      code:
        type: string
      userId:
        type: string
      userName:
        type: string
    type: object
  xxx_SessionService_models.ValidateSessionCodeReq:
    properties:
      code:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Это пример API с gorilla/mux и swaggo
  title: Пример API
  version: "1.0"
paths:
  /healthz:
    post:
      consumes:
      - application/json
      description: Checks if RabbitMQ and Redis services are operational.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully moved to the next question
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error (e.g. Redis or RabbitMQ down)
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Health check
      tags:
      - health
  /join:
    post:
      consumes:
      - application/json
      description: Validates a session code and returns a user token for the specified
        user if the code is valid.
      parameters:
      - description: ' Create Session req'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xxx_SessionService_models.ValidateCodeReq'
      produces:
      - application/json
      responses:
        "200":
          description: User token in JSON format
          schema:
            $ref: '#/definitions/xxx_SessionService_models.SessionCreateResponse'
        "400":
          description: Invalid code
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "405":
          description: Only GET method is allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Validate session code
      tags:
      - sessions
  /session/{id}/end:
    post:
      consumes:
      - application/json
      description: Delete session from redis, send message to rabbit that session
        deleted
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully moved to the next question
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: delete session, send message to rabbit
      tags:
      - sessions
  /session/{id}/nextQuestion:
    post:
      consumes:
      - application/json
      description: Advances to the next question in the session identified by the
        provided code.
      parameters:
      - description: Session ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully moved to the next question
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Move to the next question
      tags:
      - sessions
  /sessions:
    post:
      consumes:
      - application/json
      description: Creates a new session and returns an admin token for the specified
        user by userId.
      parameters:
      - description: ' Create Session req'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xxx_SessionService_models.CreateSessionReq'
      produces:
      - application/json
      responses:
        "200":
          description: Admin token in JSON format
          schema:
            $ref: '#/definitions/xxx_SessionService_models.SessionCreateResponse'
        "405":
          description: Method not allowed, only GET is allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Create a new session and get an admin token
      tags:
      - sessions
  /sessionsMock:
    post:
      consumes:
      - application/json
      description: Creates a new session and returns an admin token for the specified
        user by userId.
      parameters:
      - description: ' Create Session req'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xxx_SessionService_models.CreateSessionReq'
      produces:
      - application/json
      responses:
        "200":
          description: Admin token in JSON format
          schema:
            $ref: '#/definitions/xxx_SessionService_models.SessionCreateResponse'
        "405":
          description: Method not allowed, only GET is allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Create a new session and get an admin token. Mock endpoint, no req
        to another service
      tags:
      - sessions
  /start:
    post:
      consumes:
      - application/json
      description: Starts a session using the provided session ID.
      parameters:
      - description: Session ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Session started successfully
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Start a session
      tags:
      - sessions
  /validate:
    post:
      consumes:
      - application/json
      description: Validates a session code and returns a user token for the specified
        user if the code is valid.
      parameters:
      - description: ' Create Session req'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xxx_SessionService_models.ValidateSessionCodeReq'
      produces:
      - application/json
      responses:
        "400":
          description: Invalid code
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "405":
          description: Only GET method is allowed
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/xxx_SessionService_models.ErrorResponse'
      summary: Validate session code
      tags:
      - sessions
swagger: "2.0"
