apiVersion: v1
kind: Service
metadata:
  name: session
spec:
  selector:
    app.kubernetes.io/name: "session"
  ports:
  - protocol: TCP
    port: 8081 # Service port
    targetPort: 8081 # Pod port
