name: Migrator CI/CD

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      push-to-docker:
        description: "Also push Docker image when manually requested"
        required: false
        type: boolean
    outputs:
      image:
        value: ${{ jobs.build-push.outputs.image }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_LATEST: ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.service-name }}:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set short SHA and image name
      id: set-short-sha
      run: |
        SHORT_SHA="${GITHUB_SHA::7}"
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        echo "IMAGE_SHA=${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.service-name }}:$SHORT_SHA" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      working-directory: backend-python/shared
      run: |
        docker build -t $IMAGE_SHA -t $IMAGE_LATEST .

    - name: Push Docker image
      if: github.ref == 'refs/heads/main' || inputs.push-to-docker == true
      run: |
        docker push $IMAGE_SHA
        docker push $IMAGE_LATEST

    - name: Set output image
      id: out
      run: echo "image=$IMAGE_SHA" >> $GITHUB_OUTPUT

    outputs:
      image: ${{ steps.out.outputs.image }}
