name: Migrator CI/CD

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_SHA: ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.service-name }}:${{ github.sha }}
      IMAGE_LATEST: ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.service-name }}:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      working-directory: backend-python/shared
      run: |
        docker build -t $IMAGE_SHA -t $IMAGE_LATEST .

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker push $IMAGE_SHA
        docker push $IMAGE_LATEST

    - name: Set output image
      id: out
      run: echo "::set-output name=image::$IMAGE_SHA"

    outputs:
      image: ${{ steps.out.outputs.image }}
